In [88]:
import numpy as np
import pandas as pd

In [2]:
# Creating the List 
lists = [1,2,3,4,5]

In [3]:
lists

[1, 2, 3, 4, 5]

In [4]:
# Now putting the values in NUMPY

In [5]:
arr = np.array(lists)
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
# Memory Address of list

arr.data

In [8]:
print(type(arr.data))

<class 'memoryview'>


In [9]:
type(arr)

numpy.ndarray

In [10]:
#Data type of Array
arr.dtype

dtype('int32')

In [11]:
# Convert integer to float 
arr.astype(float)

array([1., 2., 3., 4., 5.])

In [12]:
arr.dtype

dtype('int32')

In [13]:
# Arrange the value in Descending pattern

arr = np.arange(100,10,-10)

In [14]:
arr

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [15]:
arr.shape  # Shape of array

(9,)

In [16]:
# Array size
arr.size

9

In [17]:
arr.ndim

1

In [18]:
arr.itemsize

4

In [19]:
# Odd number
arr = np.arange(1,10)
arr[arr%2 ==1]

array([1, 3, 5, 7, 9])

In [20]:
# Even Number

arr = np.arange(1,10)
arr[arr%2 ==0]

array([2, 4, 6, 8])

In [21]:
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [22]:
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [23]:
f1 = np.random.uniform(5,10,size=(10))
f1

array([6.96058759, 6.71589008, 8.64524854, 7.19286122, 5.29838948,
       6.99022128, 8.68997703, 5.91245865, 5.87725878, 7.65775687])

In [24]:
np.floor(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [25]:
np.trunc(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [26]:
f1.astype(int)

array([6, 6, 8, 7, 5, 6, 8, 5, 5, 7])

In [27]:
for index,value in np.ndenumerate(arr):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9


In [28]:
arr2 = np.arange(1,20)

In [29]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [30]:
arr2.sum()

190

In [31]:
arr2.min()

1

In [32]:
arr2.max()

19

In [33]:
# Find the min index from array
arr2.argmin()

0

In [34]:
# find the max index from array
arr2.argmax()

18

In [35]:
# Find the Mean from all number from array
arr2.mean()

10.0

In [36]:
np.median(arr2)

10.0

In [37]:
np.var(arr2)

30.0

In [38]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
A.sum()

45

In [41]:
A.max()

9

In [42]:
A.min()

1

In [45]:
np.amax(A,axis=0)

array([7, 8, 9])

In [44]:
np.amin(A,axis=1)

array([1, 4, 7])

In [48]:
A.shape

(3, 3)

In [50]:
for index , values in np.ndenumerate(A):
    print(index , values)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


## Reading the Elements of Array

In [54]:
a = np.array([1,2,3,4,5])

In [55]:
a

array([1, 2, 3, 4, 5])

In [56]:
a[:]

array([1, 2, 3, 4, 5])

In [57]:
a[-1]

5

In [58]:
a[-2]

4

In [59]:
a[-3]

3

In [64]:
a[-3:]

array([3, 4, 5])

In [65]:
a[-3:-1]

array([3, 4])

## Replace elements of the Array

In [66]:
ar = np.arange(1,20)

In [67]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [71]:
# Now replace the Even number with zero 

result = np.where(ar %2 == 0,0,ar)
print(result)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


## Reading for NULL

In [73]:
arr1 = np.array([10,np.nan,30,np.nan])

In [74]:
arr1

array([10., nan, 30., nan])

In [76]:
np.isnan(arr1)

array([False,  True, False,  True])

In [80]:
arr1[np.isnan(arr1)] = 99

In [81]:
arr1

array([10., 99., 30., 99.])

### Working with DataFrame

In [86]:
lists = np.array([[1,np.nan,3,np.nan,5],[6,np.nan,8,np.nan,10],[11,np.nan,13,np.nan,14]])

In [87]:
lists

array([[ 1., nan,  3., nan,  5.],
       [ 6., nan,  8., nan, 10.],
       [11., nan, 13., nan, 14.]])

In [90]:
df = pd.DataFrame(lists)

In [91]:
df

0   1     2   3     4
0   1.0 NaN   3.0 NaN   5.0
1   6.0 NaN   8.0 NaN  10.0
2  11.0 NaN  13.0 NaN  14.0

In [92]:
np.isnan(df)

0     1      2     3      4
0  False  True  False  True  False
1  False  True  False  True  False
2  False  True  False  True  False

In [93]:
np.where(np.isnan(df))

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 3, 1, 3, 1, 3], dtype=int64))

In [96]:
a = np.zeros(20)

In [97]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [99]:
a.shape

(20,)

In [110]:
a = np.zeros(20).reshape(4,-1)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [111]:
a.shape

(4, 5)

In [114]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [115]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
b[0,:]

array([1, 2, 3])

In [120]:
b[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [121]:
b[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])